/// Flutter icons MilleSanders
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MilleSanders
///      fonts:
///       - asset: fonts/MilleSanders.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MilleSanders {
  MilleSanders._();

  static const _kFontFam = 'MilleSanders';
  static const _kFontPkg = null;

  static const IconData iconfinder_facebook_messenger = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_shop = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_info = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_blog = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_cards = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_talk = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_shipping = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_environment = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_choose = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_back = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconfinder_mail = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_filters = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bio = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leisure = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData software = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stationery = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData talk = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meditation = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mindful = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motivation = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nature = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData productivity = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData craft = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deep = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData large = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photos = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planning = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podcast = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData random = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendship = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organize = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData priority = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData think = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData write = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData advice = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData office = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handwerk = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData growthdecks_logo_v2_ohnetext_04 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData growthdecks_logo_v2_03 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_bookmark = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_peak = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_quotes = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_share = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_tips = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_unlock = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_whatsapp = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_write = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_hub = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_idea = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_login_filled = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_login = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_love = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_messenger = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_money = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_motivation = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_overview = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_exit = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_millesanders = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_account = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_authorization = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_business_idea = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowright = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowleft = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
