# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ios_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_app
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'RxFirebase/Firestore'
  pod 'CodableFirebase'

  target 'ios_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_appUITests' do
    # Pods for testing
  end

end
